feat: testing

diff --git a/.github/workflows/terragrunt.yml b/.github/workflows/terragrunt.yml
--- a/.github/workflows/terragrunt.yml
+++ b/.github/workflows/terragrunt.yml
@@ -36,45 +36,21 @@ jobs:
           tofu_version: ${{ env.tofu_version }}
           tg_version: ${{ env.tg_version }}
           tg_dir: ${{ env.working_dir }}
-          tg_command: 'plan -out=plan.out'
+          tg_command: 'plan -out=${{ github.workspace }}/plan.out'
+          tg_comment: 'true'
 
       - name: List Files in Directory
-        run: ls -al
-
-      - name: Debug Plan Output
-        run: |
-          if [ -f "plan.out" ]; then
-            echo "plan.out exists.";
-          else
-            echo "plan.out does not exist.";
-            exit 1;
-          fi
-
-      - name: Output Plan Logs
-        run: cat plan.out || echo "Plan logs not found."
-      
+        run: ls ${{ github.workspace }} -al
 
       - name: Output Plan Logs terragrunt
-        run: cat terragrunt/plan.out || echo "Plan logs not found in terragrunt dir."
+        run: cat ${{ github.workspace }}/plan.out || echo "Plan logs not found in terragrunt dir."
 
       - name: Upload Plan Artifact
         uses: actions/upload-artifact@v4.6.2
         with:
           name: terragrunt-plan
-          path: terragrunt/plan.out
+          path: ${{ github.workspace }}/plan.out
 
-      - name: Post Plan to PR
-        uses: actions/github-script@v6
-        with:
-          script: |
-            const fs = require('fs');
-            const plan = fs.readFileSync('plan.out', 'utf8');
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: `### Terragrunt Plan\n\n\`\`\`\n${plan}\n\`\`\``
-            });
 
   deploy:
     runs-on: ubuntu-latest
