feat: testing

diff --git a/.github/workflows/terragrunt.yml b/.github/workflows/terragrunt.yml
--- a/.github/workflows/terragrunt.yml
+++ b/.github/workflows/terragrunt.yml
@@ -3,8 +3,8 @@ on:
   - pull_request
 
 env:
-  tofu_version: '1.8.1'
-  tg_version: '0.67.0'
+  tg_version: '0.77.17'
+  tf_version: '1.11.4'
   working_dir: 'terragrunt'
 
 jobs:
@@ -17,7 +17,7 @@ jobs:
       - name: Check terragrunt HCL
         uses: gruntwork-io/terragrunt-action@v2
         with:
-          tofu_version: ${{ env.tofu_version }}
+          tf_version: ${{ env.tf_version }}
           tg_version: ${{ env.tg_version }}
           tg_dir: ${{ env.working_dir }}
           tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'
@@ -33,23 +33,23 @@ jobs:
         id: terragrunt-plan
         uses: gruntwork-io/terragrunt-action@v2
         with:
-          tofu_version: ${{ env.tofu_version }}
+          tf_version: ${{ env.tf_version }}
           tg_version: ${{ env.tg_version }}
           tg_dir: ${{ env.working_dir }}
-          tg_command: 'plan -out=/github/workspace/terragrunt/plan.out --terragrunt-log-level debug --terragrunt-debug'
+          tg_command: 'plan -out=/tmp/plan.out --terragrunt-log-level debug --terragrunt-debug'
           tg_comment: 'true'
 
       - name: List Files in Directory
         run: ls ${{ github.workspace }} -al
 
       - name: Output Plan Logs terragrunt
-        run: cat /github/workspace/terragrunt/plan.out || echo "Plan logs not found in terragrunt dir."
+        run: cat /tmp/plan.out || echo "Plan logs not found in terragrunt dir."
 
       - name: Upload Plan Artifact
         uses: actions/upload-artifact@v4.6.2
         with:
           name: terragrunt-plan
-          path: /github/workspace/terragrunt/plan.out
+          path: /tmp/plan.out
 
 
   deploy:
@@ -68,7 +68,7 @@ jobs:
       - name: Deploy
         uses: gruntwork-io/terragrunt-action@v2
         with:
-          tofu_version: ${{ env.tofu_version }}
+          tf_version: ${{ env.tf_version }}
           tg_version: ${{ env.tg_version }}
           tg_dir: ${{ env.working_dir }}
           tg_command: 'apply plan.out'
